# -*- coding: utf-8 -*-
"""oss개발개인과제 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GAz7LDZuE_qee4q8fGkTwDkjgUQaOCfA
"""

from sklearn import datasets

# 데이터셋 로드
cancer = datasets.load_breast_cancer()
print(cancer)

# 훈련데이터와 테스트 데이터 분리
from sklearn.model_selection import train_test_split

X = cancer.data
y = cancer.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=4)

print(X_train.shape)
print(X_test.shape)

# 학습
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train, y_train)

#평가
from sklearn import metrics
y_pred = knn.predict(X_test)

scores = metrics.accuracy_score(y_test, y_pred)
print(scores)