# -*- coding: utf-8 -*-
"""oss개발 개인과제 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a1OCchEAlv1A4ynKnzmZlIKMwD7WpeQv
"""

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

# 데이터셋 로드
cancer = datasets.load_breast_cancer()

# 데이터 분리
X = cancer.data
y = cancer.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=4)

print(X_train.shape)
print(X_test.shape)

for k in [3, 9, 15]:
  knn = KNeighborsClassifier(n_neighbors=k)
  knn.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  scores = metrics.accuracy_score(y_test, y_pred)
  print(f"n_neighbors={k}: {scores}")